name: ABAPLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: abaplint
        uses: abaplint/abaplint@v2
        with:
          abaplint_version: latest
